### ISSUE TITLE
Use NTP instead of Local Time

### ISSUE THREAD

**Issue by kubo6472** [lexogrine/auto-replay-generator#1]
Keep everything in sync by directly utilizing the same network time server, instead of relying on the unreliable windows system time, which sometimes jumps to UTC-12 on every reboot.

**Comment by osztenkurden** [comment]
It will be addressed soon

**Comment by osztenkurden** [comment]
@kubo6472 Done, you just need ARG 1.4.0 with LHM 3.8.0. Upon connecting ARG will calculate an offset between both PCs and apply it to kill timers.
